version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    container_name: ghs_bot
    env_file: .env
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      TOML_PATH: /app/analecta/laffey.toml
      DB_CACHE_PATH: /app/.cache/users.json
      NOTIFY_INTERVAL: 10000
    volumes:
      - ./.cache:/app/.cache
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    container_name: ghs_web
    env_file: .env
    environment:
      HOST_NAME: example.com
      CLIENT_ID: not_found
      CLIENT_SECRET: not_found
    ports:
      - 3000:3000
