Subscribe = "了解、任務があり次第連絡する。"
Unsubscribe = "了解、頼まれたらまた連絡するね。"
NotSubscribed = "司令官、通知の登録はしてないよ？"
MarkAsRead = "既読にしておくね。"
BringIssue = "司令官に連絡みたいだよ。"
BringPR = "コードレビューが終わったら、一緒にウイスキーでもどうだい？"
BringBranch = "この世界線には力を感じる。ブランチというのか？ Хорошо."
BringRepo = "司令官、頼まれた資料だよ。"
NothingToBring = "任務は無いみたいだね。"
EnumIssue = "さあ、任務を始めようか。"
EnumPR = "司令官のサインが必要な書類がいくつかあるみたいだよ。"
EnumBranch = "司令官の作ったブランチがこんなに。"
CreatingIssue = "Issue 報告してくれるんだね、Спасибо."
InvalidToken = "このトークンは使えないみたいだね。"

Failure = ["司令官、なにか問題が発生したようだ。", "こちらの落ち度だ、申し訳ない。", "デグレードがあったみたいだね。"]

Flavor = [
  "司令官、何だい？",
  "そろそろ戻ってもいいかな。",
  "何？司令官。",
  "Ура!",
  "眠かったらどうぞ。私の膝を貸そうか。",
  "司令官、今日も一日、お疲れ様。",
]

BlackPattern = "[精孕母乳味女こっぽんイコッポンｺｯﾎﾟﾝEHKTNehktn:○●_|\\*]"
CallPattern = "ひびき|はらちょ|はらしょ|ハラショ|Bep|Вер|別府"

HelpMessage = """```
/ghr (所属/)レポジトリ名 ==> リポジトリを持ってくるよ
/ghb (所属/)レポジトリ名 ブランチ名 ==> ブランチを持ってくるよ
/ghi (所属/)レポジトリ名(/数字) ==> Issue を持ってくるよ
/ghp (所属/)レポジトリ名(/数字) ==> PR を持ってくるよ

/ghs GitHubのID 通知トークン ==> GitHub 通知を DM にお届けするよ
  通知トークンはこちらから作ってくれ
  https://github.com/settings/tokens/new?scopes=repo&description=GitHub%20Secretary
/ghu ==> GitHub 通知を DM にお届けしなくなるよ
/ghm 通知ID ==> GitHub 通知を既読にするよ
  通知ID は、私が送ったメッセージに入ってる
  #012345678 の # 以降の数字部分だ
```"""
ErrorMessage = "司令官、コマンドが分からなければ `/gh?` から見てくれ。"
